"""
PhishLens — ML Classifier Service
Round 3, Module 1

Architecture:
    TF-IDF Vectorizer (max 5000 features, 1-2 ngrams, sublinear TF)
    + Multinomial Naive Bayes

Model files are stored in backend/models/ and are generated by running:
    python models/train_classifier.py

This service is intentionally standalone — it is NOT yet wired into any
API endpoint. Integration happens in Round 3, Module 2 (hybrid risk engine).
"""

import os
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

# Resolve the absolute path to backend/models/ regardless of working directory.
_MODELS_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "models")
_MODEL_PATH      = os.path.normpath(os.path.join(_MODELS_DIR, "phishing_model.pkl"))
_VECTORIZER_PATH = os.path.normpath(os.path.join(_MODELS_DIR, "tfidf_vectorizer.pkl"))


class MLClassifier:
    """
    Lightweight phishing classifier using TF-IDF + Multinomial Naive Bayes.

    Loads pre-trained model and vectorizer from backend/models/ at startup.
    Falls back to a safe stub response when model files are unavailable so
    that the API continues to work without trained artifacts (Round 2 compat).

    predict() is intentionally NOT wired into any API endpoint yet.
    Integration is scheduled for Round 3, Module 2.
    """

    def __init__(self):
        self._model      = None
        self._vectorizer = None
        self._loaded     = False
        self._load_model()

    def _load_model(self) -> None:
        """
        Attempts to load the trained model and vectorizer from disk.
        Fails silently with a warning so the service stays available.
        """
        try:
            import joblib  # imported here to keep the class importable even
                           # before scikit-learn is installed during dev setup

            if not os.path.isfile(_MODEL_PATH):
                logger.warning(
                    "MLClassifier: model file not found at '%s'. "
                    "Run models/train_classifier.py to generate it. "
                    "Falling back to stub predictions.",
                    _MODEL_PATH,
                )
                return

            if not os.path.isfile(_VECTORIZER_PATH):
                logger.warning(
                    "MLClassifier: vectorizer file not found at '%s'. "
                    "Run models/train_classifier.py to generate it. "
                    "Falling back to stub predictions.",
                    _VECTORIZER_PATH,
                )
                return

            self._model      = joblib.load(_MODEL_PATH)
            self._vectorizer = joblib.load(_VECTORIZER_PATH)
            self._loaded     = True
            logger.info("MLClassifier: model loaded successfully from '%s'.", _MODEL_PATH)

        except Exception as exc:  # pragma: no cover
            logger.error("MLClassifier: failed to load model — %s. Using stub.", exc)

    @property
    def is_loaded(self) -> bool:
        """Returns True when the real model is loaded and ready."""
        return self._loaded

    @staticmethod
    def supports_language(language: str) -> bool:
        """The bundled model was trained solely on English examples."""
        return language == "en"

    def predict(self, content: str, language: str = "en") -> Dict[str, Any]:
        """
        Runs the phishing classifier on the given text content.

        Args:
            content: Raw text string (message body, email, SMS, etc.)

        Returns:
            A dict with:
                prediction  — "safe" or "phishing"
                probability — float in [0.0, 1.0], confidence in the prediction
                model_ready — bool, whether the real model was used
        """
        # Do not let an English-only model influence assessments in another
        # language merely because its vectorizer accepts Unicode input.
        if not self.supports_language(language):
            return {
                "prediction": "safe",
                "probability": 0.0,
                "model_ready": False,
            }

        # --- Guard: empty or non-string input ---
        if not content or not isinstance(content, str) or not content.strip():
            return {
                "prediction":  "safe",
                "probability": 0.0,
                "model_ready": self._loaded,
            }

        # --- Stub fallback when model is not loaded ---
        if not self._loaded:
            return {
                "prediction":  "safe",
                "probability": 0.0,
                "model_ready": False,
            }

        try:
            # Vectorize the input text
            features = self._vectorizer.transform([content.strip()])

            # Get predicted class label
            prediction = self._model.predict(features)[0]   # "safe" | "phishing"

            # Get probability for the predicted class
            probabilities = self._model.predict_proba(features)[0]
            classes       = list(self._model.classes_)
            pred_index    = classes.index(prediction)
            probability   = float(probabilities[pred_index])

            return {
                "prediction":  prediction,
                "probability": round(probability, 4),
                "model_ready": True,
            }

        except Exception as exc:  # pragma: no cover
            logger.error("MLClassifier.predict() failed — %s. Returning stub.", exc)
            return {
                "prediction":  "safe",
                "probability": 0.0,
                "model_ready": False,
            }


# Module-level singleton — imported by app/services/__init__.py
ml_classifier = MLClassifier()
